### ISSUE TITLE
README file not updated

### ISSUE THREAD

**Issue by andela-bmakinwa** [andela-oosiname/mgt#24]
The README file should be updated to reflect changes in the application.
For example, the model section should be updated to have the `property` method instead of the `attribute` method which was earlier used in the application.

**Comment by andela-bmakinwa** [comment]
Also in the controllers section, the class name should be `TodoController` as against `todoController` which is there at the moment.

**Comment by andela-oosiname** [comment]
This issue and all related ones have been fixed
